packages:
  - apps/*
  - packages/*

# Other Settings (https://pnpm.io/settings#other-settings)
shellEmulator: true

# Build settings (https://pnpm.io/settings#build-settings)
allowBuilds:
  esbuild: true
  unrs-resolver: true
verifyDepsBeforeRun: install
